scheme: "Orionis"
author: "Protesilaos Stavrou (https://protesilaos.com/orionis)"

# Colour values
valuedbg: "1F2A2D" # Dark background
valuedhl: "2F3A3D" # Dark highlight
valuedt2: "5F6A6D" # Dark bg text secondary
valuedt1: "8F9A9D" # Dark bg text primary
valuelbg: "EFF1F3" # Light background
valuelhl: "DFE1E3" # Light highlight
valuelt2: "8F9193" # Light bg text secondary
valuelt1: "5F6163" # Light bg text primary
valuered: "974F6C" # Red
valueora: "9D7427" # Orange
valueyel: "9A8F0C" # Yellow
valuegre: "5B935B" # Green
valuecya: "52A6AD" # Cyan
valueblu: "4D8AB3" # Blue
valuevio: "7E7EAD" # Violet
valuemag: "AD6E8F" # Magenta

# Visual order used for colour mapping
valuep1: "AD6E8F" # Magenta
valuep2: "7E7EAD" # Violet
valuep3: "4D8AB3" # Blue
values1: "52A6AD" # Cyan
values2: "5B935B" # Green
valuet1: "974F6C" # Red
valuet2: "9D7427" # Orange
valuet3: "9A8F0C" # Yellow

# IMPORTANT Terminal values follow this sequence in the relevant templates:
# 0=dhl; 1=red; 2=gre; 3=yel; 4=blu; 5=mag; 6=cya; 7=lhl;
# 8=dbg; 9=ora; 10=lt1; 11=dt2; 12=lt2; 13=vio; 14=dt1; 15=lbg.
# Based on the colour mapping of Solarized for terminals such those of GNOME and XFCE4.

# Terminal codes for colour values
# This presupposes that the terminal sequence is followed
valuecdbg: "8"
valuecdhl: "0"
valuecdt2: "11"
valuecdt1: "14"
valueclbg: "15"
valueclhl: "7"
valueclt2: "12"
valueclt1: "10"
valuecred: "1"
valuecora: "9"
valuecyel: "3"
valuecgre: "2"
valueccya: "6"
valuecblu: "4"
valuecvio: "13"
valuecmag: "5"

# Terminal accent colours corresponding to the visual order
valuecp1: "5"
valuecp2: "13"
valuecp3: "4"
valuecs1: "6"
valuecs2: "2"
valuect1: "1"
valuect2: "9"
valuect3: "3"
